apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: matheusnb/argocd
  newTag: bfae9c5c2930e77209a50693c27efc91999b37f0
